export const teamMembers = [
  { id: 'user-1', name: 'Alice', availability: 8 },
  { id: 'user-2', name: 'Bob', availability: 6 },
  { id: 'user-3', name: 'Charlie', availability: 8 },
];

export const tasks = [
  {
    id: 'task-1',
    name: 'Implement user authentication',
    deadline: '2024-08-10',
    dependencies: [],
    assignee: 'user-1',
    priority: 'high' as 'high' | 'medium' | 'low',
    status: 'in progress' as 'open' | 'in progress' | 'completed',
    estimatedHours: 16,
  },
  {
    id: 'task-2',
    name: 'Design database schema',
    deadline: '2024-08-05',
    dependencies: [],
    assignee: 'user-2',
    priority: 'high' as 'high' | 'medium' | 'low',
    status: 'completed' as 'open' | 'in progress' | 'completed',
    estimatedHours: 8,
  },
  {
    id: 'task-3',
    name: 'Setup CI/CD pipeline',
    deadline: '2024-08-15',
    dependencies: ['task-2'],
    assignee: 'user-3',
    priority: 'medium' as 'high' | 'medium' | 'low',
    status: 'open' as 'open' | 'in progress' | 'completed',
    estimatedHours: 12,
  },
  {
    id: 'task-4',
    name: 'Develop API for tasks',
    deadline: '2024-08-20',
    dependencies: ['task-1', 'task-2'],
    assignee: 'user-1',
    priority: 'medium' as 'high' | 'medium' | 'low',
    status: 'open' as 'open' | 'in progress' | 'completed',
    estimatedHours: 24,
  },
  {
    id: 'task-5',
    name: 'Create landing page',
    deadline: '2024-08-12',
    dependencies: [],
    assignee: 'user-2',
    priority: 'low' as 'high' | 'medium' | 'low',
    status: 'in progress' as 'open' | 'in progress' | 'completed',
    estimatedHours: 8,
  },
  {
    id: 'task-6',
    name: 'Write documentation',
    deadline: '2024-08-25',
    dependencies: ['task-4'],
    assignee: 'user-3',
    priority: 'low' as 'high' | 'medium' | 'low',
    status: 'open' as 'open' | 'in progress' | 'completed',
    estimatedHours: 10,
  },
];
